"""Add Photo model

Revision ID: 095387108e58
Revises: 7149a7f75b46
Create Date: 2025-11-30 16:07:10.889735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095387108e58'
down_revision = '7149a7f75b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=140), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('camera_make', sa.String(length=100), nullable=True),
    sa.Column('camera_model', sa.String(length=100), nullable=True),
    sa.Column('lens', sa.String(length=100), nullable=True),
    sa.Column('focal_length', sa.String(length=50), nullable=True),
    sa.Column('aperture', sa.String(length=50), nullable=True),
    sa.Column('shutter_speed', sa.String(length=50), nullable=True),
    sa.Column('iso', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo')
    # ### end Alembic commands ###
