"""Add Profile table

Revision ID: ac7ba78dc1f3
Revises: 095387108e58
Create Date: 2025-11-30 17:17:29.010937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac7ba78dc1f3'
down_revision = '095387108e58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=140), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=120), nullable=True),
    sa.Column('instagram', sa.String(length=120), nullable=True),
    sa.Column('facebook', sa.String(length=120), nullable=True),
    sa.Column('threads', sa.String(length=120), nullable=True),
    sa.Column('bluesky', sa.String(length=120), nullable=True),
    sa.Column('mastodon', sa.String(length=120), nullable=True),
    sa.Column('x', sa.String(length=120), nullable=True),
    sa.Column('linkedin', sa.String(length=120), nullable=True),
    sa.Column('youtube', sa.String(length=120), nullable=True),
    sa.Column('tiktok', sa.String(length=120), nullable=True),
    sa.Column('kofi', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
